'use client';
import { FormEvent, useState } from 'react';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
type Tab='discover'|'analyze'|'integrations';

type Preview={
 company_name:string; product_summary:string; confidence:number;
 recommended_countries:string[]; recommended_industries:string[]; recommended_functions:string[]; recommended_titles:string[];
 headcount_min:number; headcount_max:number; account_limit:number; signal_window_days:number;
 rationale:string; segments:any[]; trigger_signals:any[];
};

export default function Home(){
 const [tab,setTab]=useState<Tab>('discover'); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false); const [previewLoading,setPreviewLoading]=useState(false); const [error,setError]=useState('');
 const [website,setWebsite]=useState(''); const [deckText,setDeckText]=useState(''); const [deckStatus,setDeckStatus]=useState(''); const [preview,setPreview]=useState<Preview|null>(null);
 const [progress,setProgress]=useState(''); const [progressPct,setProgressPct]=useState(0);

 async function uploadDeck(file?:File){if(!file)return;setDeckStatus('Reading deck…');setError('');setPreview(null);const fd=new FormData();fd.append('file',file);try{const r=await fetch(`${API}/discovery/deck`,{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Deck upload failed');setDeckText(j.text||'');setDeckStatus(`${j.filename} · ${Number(j.characters||0).toLocaleString()} characters loaded`)}catch(x:any){setDeckText('');setDeckStatus('');setError(x.message||'Deck upload failed')}}

 async function generatePreview(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!deckText){setError('Please upload a readable product deck first.');return}setPreviewLoading(true);setError('');setData(null);setProgress('');try{const r=await fetch(`${API}/discovery/icp-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({website,deck_text:deckText})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Could not generate ICP preview');setPreview(j)}catch(x:any){setError(x.message||'Could not generate ICP preview')}finally{setPreviewLoading(false)}}

 async function startDiscovery(){if(!preview)return;setLoading(true);setError('');setData(null);setProgress('Starting discovery…');setProgressPct(2);const body={seller:{website,company_name:preview.company_name||null,deck_text:deckText,product_hint:preview.product_summary||null},icp:{countries:preview.recommended_countries||[],industries:preview.recommended_industries||[],target_functions:preview.recommended_functions||[],target_titles:preview.recommended_titles||[],headcount_min:preview.headcount_min||50,headcount_max:preview.headcount_max||5000,account_limit:preview.account_limit||10,signal_window_days:preview.signal_window_days||90}};try{const r=await fetch(`${API}/discovery/runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Could not start discovery');const id=j.run_id;setProgressPct(Number(j.progress||2));for(let i=0;i<240;i++){await sleep(3000);const s=await fetch(`${API}/discovery/runs/${id}`,{cache:'no-store'});const state=await s.json();if(!s.ok)throw new Error(state.detail||'Could not read discovery status');setProgress(`${state.stage||state.status} · Run #${id}`);setProgressPct(Number(state.progress||5));if(state.status==='completed'){setData(state.result);setProgress(`Complete · Run #${id}`);setProgressPct(100);return}if(state.status==='failed')throw new Error(state.error||'Discovery failed')}throw new Error('Discovery is still running. Your run is saved; refresh later rather than starting another run.')}catch(x:any){setError(x.message||'Discovery failed')}finally{setLoading(false)}}

 function resetSeller(){setPreview(null);setData(null);setProgress('');setProgressPct(0)}

 return <div className="shell"><aside className="sidebar"><div className="brand">Scalee <span>OpportunityOS</span></div><div className="tag">Universal Buying-Signal Intelligence</div><div className="nav"><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>🔥 Find Opportunities</button><button className={tab==='analyze'?'active':''} onClick={()=>setTab('analyze')}>◎ Opportunity Analyst</button><button className={tab==='integrations'?'active':''} onClick={()=>setTab('integrations')}>⚙ Integrations</button></div></aside><main className="main"><div className="topbar"><div><div className="eyebrow">Universal Discovery V1</div><h1 className="title">Give us your website and deck. We do the rest.</h1><div className="muted">OpportunityOS learns your product, generates the ICP, finds buying signals, ranks accounts and maps buyers.</div></div><span className="pill">AI-generated ICP · Human approved</span></div>{error&&<div className="error">{error}</div>}{progress&&<div className="card progressCard"><div className="progressHeader"><strong>{progress}</strong><span className="small">{progressPct}%</span></div><div className="progressTrack"><div className="progressFill" style={{width:`${Math.min(100,Math.max(0,progressPct))}%`}}/></div><div className="small">This run is persisted. You can close the page without losing the result.</div></div>}
 {tab==='discover'&&<><div className="grid"><section className="card"><div className="stepLabel">Step 1 of 2</div><h2>Teach OpportunityOS your product</h2><p className="muted">No ICP form. No keyword setup. No manual filters.</p><form onSubmit={generatePreview}><div className="field"><label>Company website</label><input value={website} onChange={e=>{setWebsite(e.target.value);setPreview(null)}} name="website" type="url" placeholder="https://yourcompany.com" required/></div><div className="field"><label>Product / sales deck</label><input type="file" accept=".pdf,.pptx,.txt,.md" onChange={e=>uploadDeck(e.target.files?.[0])} required={!deckText}/>{deckStatus&&<span className="small successText">✓ {deckStatus}</span>}</div><button className="btn" disabled={previewLoading||!deckText}>{previewLoading?'Building your ICP…':'Generate AI ICP Preview'}</button></form></section><section className="card"><div className="stepLabel">What happens automatically</div><h2>OpportunityOS Product Brain</h2><div className="autoList"><span>01</span><p><strong>Understands the product</strong><br/><small>Problems, outcomes, use cases and differentiation</small></p><span>02</span><p><strong>Builds the ICP</strong><br/><small>Markets, industries, company size and buying committee</small></p><span>03</span><p><strong>Creates signal taxonomy</strong><br/><small>Observable events that indicate a potential buying window</small></p><span>04</span><p><strong>Finds and ranks accounts</strong><br/><small>Evidence-backed opportunities and the right buyers</small></p></div></section></div>
 {preview&&<ICPPreviewCard p={preview} loading={loading} onApprove={startDiscovery} onReset={resetSeller}/>} {data&&<Results data={data}/>}</>}
 {tab==='analyze'&&<section className="card"><h2>Opportunity Analyst</h2><p className="muted">Universal Discovery determines which accounts deserve deep analysis first.</p></section>}
 {tab==='integrations'&&<section className="card"><h2>Integration status</h2>{data?Object.entries(data.provider_status||{}).map(([k,v]:any)=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>):<div className="empty">Run discovery once to see live provider status.</div>}</section>}
 </main></div>}

function ICPPreviewCard({p,loading,onApprove,onReset}:{p:Preview,loading:boolean,onApprove:()=>void,onReset:()=>void}){return <section className="card previewCard"><div className="previewTop"><div><div className="stepLabel">Step 2 of 2 · AI-generated ICP preview</div><h2>{p.company_name}</h2><p className="hook">{p.product_summary}</p></div><div className="confidence"><b>{p.confidence}%</b><span>AI confidence</span></div></div><p className="muted previewRationale">{p.rationale}</p><div className="previewGrid"><PreviewGroup title="Markets" items={p.recommended_countries}/><PreviewGroup title="Industries" items={p.recommended_industries}/><PreviewGroup title="Buyer functions" items={p.recommended_functions}/><PreviewGroup title="Buyer titles" items={p.recommended_titles}/></div><div className="rangeBar"><span><strong>Company size</strong><br/>{p.headcount_min.toLocaleString()} – {p.headcount_max.toLocaleString()} employees</span><span><strong>Opportunity batch</strong><br/>{p.account_limit} deeply researched accounts</span><span><strong>Signal window</strong><br/>{p.signal_window_days} days</span></div><div className="sectionLabel">Priority ICP segments</div><div className="segmentGrid">{p.segments?.map((s:any,i:number)=><div className="segment" key={i}><span className="pill">{s.priority}</span><h3>{s.name}</h3><p>{s.why_fit}</p><div className="small">{s.industries?.join(' · ')}</div><div className="small">Buyers: {s.target_titles?.join(' · ')}</div><div className="sectionLabel">Buying triggers</div><div className="small">{s.buying_triggers?.join(' · ')}</div></div>)}</div><div className="sectionLabel">Dynamic buying signals OpportunityOS will watch</div><div className="signalGrid">{p.trigger_signals?.slice(0,8).map((s:any,i:number)=><div className="signalChip" key={i}><strong>{s.name}</strong><span>weight {s.weight}/10</span></div>)}</div><div className="approvalBar"><div><strong>Looks right?</strong><div className="small">Approve this ICP and OpportunityOS will use it automatically for discovery.</div></div><div className="approvalActions"><button className="ghostBtn" onClick={onReset} disabled={loading}>Change inputs</button><button className="btn" onClick={onApprove} disabled={loading}>{loading?'Discovery running…':'Approve & Find Opportunities'}</button></div></div></section>}
function PreviewGroup({title,items}:{title:string,items:string[]}){return <div><div className="sectionLabel">{title}</div><div className="chipWrap">{items?.map((x,i)=><span className="previewChip" key={i}>{x}</span>)}</div></div>}
function Results({data}:{data:any}){const a=data.accounts||[];return <section className="results"><div className="kpis"><div className="kpi"><span className="small">Candidates</span><b>{data.candidate_count}</b></div><div className="kpi"><span className="small">Researched</span><b>{data.researched_count}</b></div><div className="kpi"><span className="small">85+ hot</span><b>{a.filter((x:any)=>x.score>=85).length}</b></div><div className="kpi"><span className="small">95+ immediate</span><b>{a.filter((x:any)=>x.score>=95).length}</b></div></div><div className="card"><h2>Ranked opportunity feed</h2>{a.length?a.map((x:any)=><Account x={x} key={x.website}/>):<div className="empty">No evidence-backed opportunities met the scoring threshold in this run.</div>}</div></section>}
function Account({x}:{x:any}){return <div className="opportunity"><div className="opHead"><div><span className="pill">{String(x.tier).replaceAll('_',' ')}</span><h3>{x.company_name}</h3><div className="small">{[x.country,x.industry,x.headcount&&`${x.headcount} employees`].filter(Boolean).join(' · ')}</div></div><div className="score smallScore">{x.score}</div></div><div className="sectionLabel">Why now</div><p>{x.why_now}</p><div className="sectionLabel">Product fit</div><p>{x.product_fit}</p><div className="buyerGrid">{x.top_buyers?.slice(0,3).map((b:any,i:number)=><div className="buyer" key={i}><strong>{b.title}</strong><span className="small">{b.role.replaceAll('_',' ')}</span><p>{b.why}</p><span className="small">Channels: {b.preferred_channels?.join(' → ')}</span></div>)}</div>{x.signals?.map((s:any,i:number)=><div className="signal" key={i}><strong>{s.signal} · {s.strength}/100</strong><span>{s.why_it_matters}</span>{s.evidence?.map((e:any,j:number)=><div className="evidence" key={j}><a href={e.url} target="_blank" rel="noreferrer">{e.title} ↗</a><div className="small">{e.source_type} · {e.published_date||'date unknown'} · {e.confidence}% confidence</div><div>{e.snippet}</div></div>)}</div>)}</div>}
