'use client';
import { FormEvent, useState } from 'react';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const split=(v:FormDataEntryValue|null)=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
type Tab='discover'|'analyze'|'integrations';

export default function Home(){
 const [tab,setTab]=useState<Tab>('discover'); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function discover(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');setData(null);const f=new FormData(e.currentTarget);const body={seller:{website:f.get('website'),company_name:f.get('company_name')||null,deck_text:f.get('deck_text')||null,product_hint:f.get('product_hint')||null},icp:{countries:split(f.get('countries')),industries:split(f.get('industries')),target_functions:split(f.get('functions')),target_titles:split(f.get('titles')),headcount_min:Number(f.get('headcount_min')||50),headcount_max:Number(f.get('headcount_max')||5000),account_limit:Number(f.get('account_limit')||10),signal_window_days:Number(f.get('signal_window_days')||90)}};try{const r=await fetch(`${API}/discovery/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Discovery failed');setData(j)}catch(x:any){setError(x.message||'Discovery failed')}finally{setLoading(false)}}
 return <div className="shell"><aside className="sidebar"><div className="brand">Scalee <span>OpportunityOS</span></div><div className="tag">Universal Buying-Signal Intelligence</div><div className="nav"><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>🔥 Find Opportunities</button><button className={tab==='analyze'?'active':''} onClick={()=>setTab('analyze')}>◎ Opportunity Analyst</button><button className={tab==='integrations'?'active':''} onClick={()=>setTab('integrations')}>⚙ Integrations</button></div></aside><main className="main"><div className="topbar"><div><div className="eyebrow">Universal Discovery V1</div><h1 className="title">Find accounts with a reason to buy now.</h1><div className="muted">Seller intelligence → market discovery → verified signals → ranked accounts → buyer map.</div></div><span className="pill">Human-controlled outreach</span></div>{error&&<div className="error">{error}</div>}
 {tab==='discover'&&<><div className="grid"><section className="card"><h2>Define your market</h2><p className="muted">Give us your company. OpportunityOS learns the product and generates the signal taxonomy automatically.</p><form onSubmit={discover}><div className="row"><div className="field"><label>Your company website</label><input name="website" placeholder="https://yourcompany.com" required/></div><div className="field"><label>Company name</label><input name="company_name" placeholder="Optional"/></div></div><div className="field"><label>Company deck / product context</label><textarea name="deck_text" placeholder="Paste deck text or key product context. File upload is the next ingestion adapter."/></div><div className="field"><label>What are you selling? (optional hint)</label><input name="product_hint" placeholder="AI workflow automation, Voice AI, finance automation..."/></div><div className="field"><label>Countries / regions</label><input name="countries" defaultValue="United States, UAE, Saudi Arabia, Qatar, Kuwait, Oman, Bahrain"/></div><div className="row"><div className="field"><label>Headcount minimum</label><input name="headcount_min" type="number" defaultValue="50"/></div><div className="field"><label>Headcount maximum</label><input name="headcount_max" type="number" defaultValue="5000"/></div></div><div className="field"><label>Industries (optional)</label><input name="industries" placeholder="Leave blank for AI suggestions"/></div><div className="row"><div className="field"><label>Target functions</label><input name="functions" placeholder="Operations, Finance, Supply Chain"/></div><div className="field"><label>Target job titles</label><input name="titles" placeholder="COO, VP Operations, Head of Transformation"/></div></div><div className="row"><div className="field"><label>Accounts to deeply research</label><input name="account_limit" type="number" min="5" max="100" defaultValue="10"/></div><div className="field"><label>Signal window (days)</label><input name="signal_window_days" type="number" defaultValue="90"/></div></div><button className="btn" disabled={loading}>{loading?'Discovering + researching…':'Find Opportunities'}</button></form></section><section className="card"><h2>Product Brain</h2>{data?<Brain b={data.seller_brain}/>:<div className="empty">Run discovery to generate your dynamic Product Brain and buying-signal map.</div>}</section></div>{data&&<Results data={data}/>}</>}
 {tab==='analyze'&&<section className="card"><h2>Opportunity Analyst</h2><p className="muted">The existing single-account analyst remains available through the backend. Universal Discovery now sits upstream and determines which accounts deserve deep analysis first.</p><div className="empty">Use Find Opportunities to discover and prioritize accounts. Single-account analysis remains at <code>/api/v1/opportunities/analyze</code>.</div></section>}
 {tab==='integrations'&&<section className="card"><h2>Integration status</h2><p className="muted">Providers are optional and degrade gracefully. Configure credentials in Railway backend variables.</p>{data?Object.entries(data.provider_status||{}).map(([k,v]:any)=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>):<div className="empty">Run discovery once to see live provider status.</div>}</section>}
 </main></div>}

function Brain({b}:{b:any}){return <div><div className="sectionLabel">{b.company_name}</div><p className="hook">{b.product_summary}</p><div className="sectionLabel">Problems solved</div><p>{b.problems_solved?.join(' · ')}</p><div className="sectionLabel">Target buyers</div><p>{b.target_titles?.join(' · ')}</p><div className="sectionLabel">Dynamic signals</div>{b.trigger_signals?.map((s:any,i:number)=><div className="signal" key={i}><strong>{s.name} · weight {s.weight}/10</strong><span>{s.description}</span></div>)}</div>}
function Results({data}:{data:any}){const a=data.accounts||[];return <section className="results"><div className="kpis"><div className="kpi"><span className="small">Candidates</span><b>{data.candidate_count}</b></div><div className="kpi"><span className="small">Researched</span><b>{data.researched_count}</b></div><div className="kpi"><span className="small">85+ hot</span><b>{a.filter((x:any)=>x.score>=85).length}</b></div><div className="kpi"><span className="small">95+ immediate</span><b>{a.filter((x:any)=>x.score>=95).length}</b></div></div><div className="card"><h2>Ranked opportunity feed</h2>{a.length?a.map((x:any)=><Account x={x} key={x.website}/>):<div className="empty">No evidence-backed opportunities found in this run. Broaden filters or connect Apollo/Tavily.</div>}</div></section>}
function Account({x}:{x:any}){return <div className="opportunity"><div className="opHead"><div><span className="pill">{String(x.tier).replaceAll('_',' ')}</span><h3>{x.company_name}</h3><div className="small">{[x.country,x.industry,x.headcount&&`${x.headcount} employees`].filter(Boolean).join(' · ')}</div></div><div className="score smallScore">{x.score}</div></div><div className="sectionLabel">Why now</div><p>{x.why_now}</p><div className="sectionLabel">Product fit</div><p>{x.product_fit}</p><div className="buyerGrid">{x.top_buyers?.slice(0,3).map((b:any,i:number)=><div className="buyer" key={i}><strong>{b.title}</strong><span className="small">{b.role.replaceAll('_',' ')}</span><p>{b.why}</p><span className="small">Channels: {b.preferred_channels?.join(' → ')}</span></div>)}</div>{x.signals?.map((s:any,i:number)=><div className="signal" key={i}><strong>{s.signal} · {s.strength}/100</strong><span>{s.why_it_matters}</span>{s.evidence?.map((e:any,j:number)=><div className="evidence" key={j}><a href={e.url} target="_blank" rel="noreferrer">{e.title} ↗</a><div className="small">{e.source_type} · {e.published_date||'date unknown'} · {e.confidence}% confidence</div><div>{e.snippet}</div></div>)}</div>)}</div>}
